### ISSUE TITLE
User feedback for buttons

### ISSUE THREAD

**Issue by rub1e** [fourloops/StopwatchFO#11]
Could you add a little CSS or something to the buttons so the user gets visual feedback that that button's been pressed (I appreciate that they will see the timer start/stop, but it's nice to have some sort of button effect)

PS looks awesome generally

**Comment by otajor** [comment]
Cheers! This has been done - [see this commit](https://github.com/fourloops/StopwatchFO/commit/1e355de4c9d683bb74dc3bfad8ea5bf9470c6ff6)
