### ISSUE TITLE
Can't hit "lap" when stopped 

### ISSUE THREAD

**Issue by rub1e** [fourloops/StopwatchFO#12]
Close this issue if that's a feature not a bug...!

**Comment by franzmoro** [comment]
actually it's an intended feature. One may however discuss about whether it is useful to lap when time is stopped. we're not sure really.

**Comment by rub1e** [comment]
@franzmoro that's exactly why I allowed you to close it yourself!!

**Comment by franzmoro** [comment]
thanks @rub1e !
