### ISSUE TITLE
Syntax error on line 60 stopwatch.js

### ISSUE THREAD

**Issue by MyPitit** [fourloops/StopwatchFO#13]
In line 60 we saw this line of code `for(lap in lapObj){` and it should be `for( var lap in lapObj){`

**Comment by otajor** [comment]
Thanks @MyPitit , we realised this was why we were having some errors. [Fixed this with the same commit as the comments.](https://github.com/fourloops/StopwatchFO/commit/2a2fa1e1e4b1187ca80ac957d8af5c362980be9d)

**Comment by MyPitit** [comment]
I'm glad to know it's fixed now :+1:
