### ISSUE TITLE
stopwatch.js more comments

### ISSUE THREAD

**Issue by MyPitit** [fourloops/StopwatchFO#14]
It think it will be great to add more comments into your code, for code reviews and other team members.

**Comment by otajor** [comment]
Thanks @MyPitit . Have commented stopwatch.js and display.js.

[See this commit.](https://github.com/fourloops/StopwatchFO/commit/2a2fa1e1e4b1187ca80ac957d8af5c362980be9d)

**Comment by MyPitit** [comment]
@oturnermajor nice :)
