### ISSUE TITLE
Update file structure

### ISSUE THREAD

**Issue by katbow** [fourloops/StopwatchFO#5]
Consider grouping together similar files eg. all js files.

**Comment by franzmoro** [comment]
We just [read](https://lostechies.com/derickbailey/2012/02/02/javascript-file-folder-structures-just-pick-one/) that it's a best practice for most app-frameworks but for pure js it isn't necessarily one.
There are only two js files now... if we had many more I would agree that it's best for clarity.

**Comment by katbow** [comment]
Fair enough, thanks for the link!
